### ISSUE TITLE
Shulker armor

### ISSUE THREAD

**Issue by Sunekaer** [WTBW-Mods/WTBW_Tools#1]
Shulker armor
recipe of Shulker shells and cobalt armor
Shulker shell is used in resistance potions so give the cobalt effect + resistance from each piece

**Comment by Naxanria** [comment]
Shulker shells making a resistance potion is not a vanilla thing. But can make if someone wears full set they can get resistance effect.

**Comment by Sunekaer** [comment]
Ah it did on FC xD
