### ISSUE TITLE
Shulker armour flight breaks on dimension travel

### ISSUE THREAD

**Issue by 016Nojr** [WTBW-Mods/WTBW_Tools#2]
When  travelling to another dimension, one piece of the shulker armour has to be unequipped and equipped for flight to work.

**Comment by Naxanria** [comment]
This is only an issue on FC, so another mod is causing it. Next update there will be a "fix" that should help with that though :)

**Comment by 016Nojr** [comment]
Gonna note some stuff here mostly for myself, but also so you can see what is up.

- Not happening in a fresh SP world, only on server, ~~will attempt a local server~~ not happening on local server, just FC
- Happening with other players on FC
- Unaffected by enchants, happening with enchanted and unenchanted armour
- Nothing appearing in logs

[GIF](https://gyazo.com/fa4d48fe3a268f2117e7e1977100cdce)
