### ISSUE TITLE
Shulker armor flight problems

### ISSUE THREAD

**Issue by lynaevm** [WTBW-Mods/WTBW_Tools#5]
I'm using the mod in Omnia and just made the shulker armor and the flight aspect has a very pronounced and peculiar wobble, especially when first starting to fly.  it is quite vertigo-inducing.  If I release the space bar during the wobble point I drift downward.  If I hold it down and keep forcing my way down, the wobble stops at about 10 blocks up and it behaves like creative flight.  Is this intended? Is there a way to disable the flight and keep the regen bonus?

**Comment by Naxanria** [comment]
That is fov changing because you go fast. Add a mod that prevents changing the field of view.
Like https://www.curseforge.com/minecraft/mc-mods/keep-fov
