### ISSUE TITLE
Slime Chunk Finder not displaying chat messages

### ISSUE THREAD

**Issue by kylania** [WTBW-Mods/WTBW_Tools#6]
In single player using FTP Omnia 1.2.0 on Java Minecraft 1.15.2 and WTBW_Tools version 1.0.19 the Slime Chunk Finder is not displaying the expected text messages to the chat log.  Durability is still used up with each attempt.

This happens in Creative Mode as well as Survival Gamemodes.

**Comment by Naxanria** [comment]
You sure you dont have the minetogether chat open? That will obscure it yes. Other than that it seems to work fine.

**Comment by kylania** [comment]
Well, I'm a fool!  Clicked over to the Commands tab and there the messages were.  Yup, it's working perfectly and I now have slimeballs, thanks! :)
